                                                                        NUMPY

In [1]:
import numpy as np

In [4]:
l = [1, 2, 3, 4]

In [6]:
#1d Array

ar1 = np.array(l)
ar1

array([1, 2, 3, 4])

In [10]:
#2D Array

ar2 = np.array([[1,2],[3,4]])
ar2

array([[1, 2],
       [3, 4]])

asarray

In [11]:
np.asarray(l)

array([1, 2, 3, 4])

asanyarray

In [12]:
np.asanyarray(l)

array([1, 2, 3, 4])

                                        Swallo Copy : copied in same space

In [13]:
a = [1,2,3,4]

In [14]:
a

[1, 2, 3, 4]

In [15]:
b = a
b

[1, 2, 3, 4]

In [16]:
b[0] = 100
b

[100, 2, 3, 4]

In [17]:
a

[100, 2, 3, 4]

In [18]:
#it modifues the value present in that memory location

                                            copy() : Deep Copy -  to avoid swallow copy

In [20]:
a

[100, 2, 3, 4]

In [22]:
d = np.copy(a)
d

array([100,   2,   3,   4])

In [23]:
a[1] = 200
a

[100, 200, 3, 4]

In [24]:
d

array([100,   2,   3,   4])

In [25]:
#d wont change becuase of Deep Copy

                                                        fromfunction()
                                                        
                                        helps us to generate array in any point of time

In [27]:
np.fromfunction(lambda i,j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [28]:
#here (3,3) = Matrix Size 
#lambda function for comparision
#by default i, j starts with 1 

                                                        fromiterable()
    
                                        helps us to generate an array from iterable function 

In [29]:
iterable = (i*i for i in range(5))

In [30]:
np.fromiter(iterable, int)

array([ 0,  1,  4,  9, 16])

                                                    fromstring()
    
                                    help us to get the string array (only on float datatype) 
                                    based on separators

In [32]:
np.fromstring("10 20 30", sep= ' ')

array([10., 20., 30.])

In [34]:
np.fromstring("1,2,3,3", sep =',')

array([1., 2., 3., 3.])

                                    ndim : to check the dimension of array
                                    
                                    size: check the size
                                    dtype
                                    shape
                                

In [41]:
ar1 = np.array([1,2,3,4,5,6])

ar2 = np.array([[1,2],[3,4]])


In [37]:
ar1.ndim

1

In [38]:
ar2.ndim

2

In [42]:
ar1.size

6

In [40]:
ar2.size

4

In [44]:
ar1.dtype

dtype('int64')

In [45]:
ar1.shape

(6,)

In [46]:
ar2.shape

(2, 2)

In [48]:
ar3 = np.array([[1,2,3.5],[10,20,30]])

In [49]:
ar3

array([[ 1. ,  2. ,  3.5],
       [10. , 20. , 30. ]])

In [50]:
ar3.shape

(2, 3)

                                                            arange()

In [52]:
np.arange(1.2,10.5)

array([ 1.2,  2.2,  3.2,  4.2,  5.2,  6.2,  7.2,  8.2,  9.2, 10.2])

In [53]:
np.arange(1.2,5.2,0.5)

array([1.2, 1.7, 2.2, 2.7, 3.2, 3.7, 4.2, 4.7])

In [54]:
list(np.arange(1.2,5.2,0.5))

[1.2, 1.7, 2.2, 2.7, 3.2, 3.7, 4.2, 4.7]

                                                        linspace()

In [55]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

                                                    zeros()

In [56]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [58]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

np.zeros((2,3,2))

                                                    ones()

In [60]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [62]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

                                            Aritmetic Operations on array

In [63]:
#eg using 1d array

on = np.ones(5)

In [64]:
on*5

array([5., 5., 5., 5., 5.])

In [65]:
on+1

array([2., 2., 2., 2., 2.])

                                                    empty()

In [66]:
np.empty(4)

array([4.9e-324, 9.9e-324, 1.5e-323, 2.0e-323])

In [68]:
np.empty((4,2))

array([[1.2, 1.7],
       [2.2, 2.7],
       [3.2, 3.7],
       [4.2, 4.7]])

                                            eye() : used for Identity Matrixes

In [71]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

                                                    linspace()
                                                    logspace()

In [72]:
np.linspace(2,4,10)

array([2.        , 2.22222222, 2.44444444, 2.66666667, 2.88888889,
       3.11111111, 3.33333333, 3.55555556, 3.77777778, 4.        ])

In [73]:
np.logspace(2,4,10)

array([  100.        ,   166.81005372,   278.25594022,   464.15888336,
         774.26368268,  1291.54966501,  2154.43469003,  3593.8136638 ,
        5994.84250319, 10000.        ])

In [74]:
np.logspace(2,4,10, base = 2)

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])