                                        Random Function

In [8]:
import numpy as np
import pandas as pd

                                        random.randn()

In [9]:
#genrate random data

np.random.randn(5)

array([-0.87550194,  0.93063307, -0.06324638, -1.13990445, -0.23143508])

In [3]:
np.random.randn(2,3)

array([[ 0.15594155,  1.16260675, -0.30591749],
       [-2.38801287,  0.51487803, -0.91098045]])

In [4]:
#Convert our random numbers to data frame

arr = np.random.randn(5,4)

In [5]:
arr

array([[-1.97177818,  1.71921755,  1.51478658, -1.57183869],
       [ 0.43630641, -0.41668842,  0.15857573,  1.42001659],
       [-0.9075007 ,  0.57247858, -0.13532448, -0.78772395],
       [ 0.84513094, -1.00978472,  0.33968428,  1.27545055],
       [-0.32601567, -0.57531352, -0.50320083, -1.55479244]])

In [6]:
df = pd.DataFrame(arr)

In [7]:
df

0         1         2         3
0 -1.971778  1.719218  1.514787 -1.571839
1  0.436306 -0.416688  0.158576  1.420017
2 -0.907501  0.572479 -0.135324 -0.787724
3  0.845131 -1.009785  0.339684  1.275451
4 -0.326016 -0.575314 -0.503201 -1.554792

In [10]:
np.random.rand(3,4)

array([[0.13626386, 0.75389771, 0.34176032, 0.67950496],
       [0.04404345, 0.45374715, 0.02749822, 0.4482431 ],
       [0.08109994, 0.0056906 , 0.52486987, 0.38198528]])

In [11]:
np.random.randint(5)

2

In [14]:
a = np.random.randint(1,100,(3,4))
a

array([[88,  7, 20, 17],
       [27, 14, 21, 89],
       [40, 61, 81, 17]])

In [15]:
df = pd.DataFrame(a)

In [16]:
df

0   1   2   3
0  88   7  20  17
1  27  14  21  89
2  40  61  81  17

                                        reshape()

In [33]:
arr1 = np.random.randint(20,60, (4,6))
arr1

array([[49, 36, 38, 44, 25, 48],
       [45, 47, 44, 23, 52, 48],
       [22, 30, 50, 49, 55, 54],
       [44, 38, 33, 44, 54, 56]])

In [35]:
arr2 = arr1.reshape((12,2))
arr2

array([[49, 36],
       [38, 44],
       [25, 48],
       [45, 47],
       [44, 23],
       [52, 48],
       [22, 30],
       [50, 49],
       [55, 54],
       [44, 38],
       [33, 44],
       [54, 56]])

                                        Indexing

In [36]:
arr1[1,1]

47

In [37]:
arr2[1,1]

44

In [44]:
arr2[2:5,1]

array([48, 47, 23])

                                        Extract Data based on Condition

In [45]:
arr = np.random.randint(1,100, (5,5))
arr

array([[37, 78,  8, 98, 68],
       [68, 14, 82, 55, 31],
       [ 4, 85, 84, 47, 65],
       [49, 28, 42, 51,  6],
       [93, 22, 69, 78, 90]])

In [60]:
#based on Condition

arr>50

array([[False,  True, False,  True,  True],
       [ True, False,  True,  True, False],
       [False,  True,  True, False,  True],
       [False, False, False,  True, False],
       [ True, False,  True,  True,  True]])

In [48]:
arr[arr>50]

array([78, 98, 68, 68, 82, 55, 85, 84, 65, 51, 93, 69, 78, 90])

In [49]:
arr

array([[37, 78,  8, 98, 68],
       [68, 14, 82, 55, 31],
       [ 4, 85, 84, 47, 65],
       [49, 28, 42, 51,  6],
       [93, 22, 69, 78, 90]])

In [58]:
#Based on position

arr[2:4,(2,4)]

array([[84, 65],
       [42,  6]])

                                        Data Manipulation

In [61]:
arr

array([[37, 78,  8, 98, 68],
       [68, 14, 82, 55, 31],
       [ 4, 85, 84, 47, 65],
       [49, 28, 42, 51,  6],
       [93, 22, 69, 78, 90]])

In [62]:
arr[0,0]

37

In [63]:
arr[0,0]  = 5000
arr

array([[5000,   78,    8,   98,   68],
       [  68,   14,   82,   55,   31],
       [   4,   85,   84,   47,   65],
       [  49,   28,   42,   51,    6],
       [  93,   22,   69,   78,   90]])