                                        Numpy Mathematical Operation

In [1]:
import numpy as np

In [5]:
arr1 = np.random.randint(1, 4, (3,3))
arr2 = np.random.randint(1, 4, (3,3))

In [6]:
arr1

array([[1, 2, 3],
       [1, 2, 2],
       [3, 3, 1]])

In [7]:
arr2

array([[1, 1, 2],
       [3, 2, 1],
       [1, 1, 2]])

Summation

In [8]:
arr1 + arr2

array([[2, 3, 5],
       [4, 4, 3],
       [4, 4, 3]])

Index Multiplication

In [10]:
arr1 * arr2

array([[1, 2, 6],
       [3, 4, 2],
       [3, 3, 2]])

Matrix Multiplication : by using @

In [11]:
arr1 @ arr2

array([[10,  8, 10],
       [ 9,  7,  8],
       [13, 10, 11]])

In [12]:
arr1 + 100

array([[101, 102, 103],
       [101, 102, 102],
       [103, 103, 101]])

In [13]:
arr1**2

array([[1, 4, 9],
       [1, 4, 4],
       [9, 9, 1]])

In [14]:
pow(arr1, 3)

array([[ 1,  8, 27],
       [ 1,  8,  8],
       [27, 27,  1]])

Broadcasting

In [15]:
arr3 = np.zeros((4,4))

In [19]:
col = np.random.randint(1,4, 4)

In [17]:
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
col

array([2, 1, 2, 2])

In [25]:
#coloumn wise addition

arr3+ col

array([[2., 1., 2., 2.],
       [2., 1., 2., 2.],
       [2., 1., 2., 2.],
       [2., 1., 2., 2.]])

In [45]:
#row wise addition

col = np.array([[1,2,3,4]])
col.T

array([[1],
       [2],
       [3],
       [4]])

In [46]:
arr3 + col

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])