                                        Array Manipulation

In [1]:
import numpy as np

In [3]:
arr = np.random.randint(1,10, (3,4))
arr

array([[5, 8, 2, 5],
       [3, 2, 3, 1],
       [4, 9, 4, 2]])

In [4]:
arr.reshape(2,6)

array([[5, 8, 2, 5, 3, 2],
       [3, 1, 4, 9, 4, 2]])

In [8]:
#Transpose of a Matrix

arr.T

array([[5, 3, 4],
       [8, 2, 9],
       [2, 3, 4],
       [5, 1, 2]])

In [7]:
#converting a 2D array to 1D array

arr.flatten()

array([5, 8, 2, 5, 3, 2, 3, 1, 4, 9, 4, 2])

                                        expand_dims()

In [9]:
arr = np.array([1,2,3,4])

In [10]:
arr.ndim

1

In [13]:
np.expand_dims(arr, axis = 1)

array([[1],
       [2],
       [3],
       [4]])

In [14]:
np.expand_dims(arr, axis = 0)

array([[1, 2, 3, 4]])

                                        Squeeze()

In [16]:
data = np.array([[1], [2], [3], [4]])

In [17]:
data

array([[1],
       [2],
       [3],
       [4]])

In [18]:
np.squeeze(arr)

array([1, 2, 3, 4])

                                        repeat()

In [21]:
arr

array([1, 2, 3, 4])

In [22]:
np.repeat(arr, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

                                        roll()
                                        
                                    to shift the data

In [24]:
arr

array([1, 2, 3, 4])

In [26]:
np.roll(arr, 2)

array([3, 4, 1, 2])

                                        diag()

In [29]:
arr

array([1, 2, 3, 4])

In [30]:
np.diag(arr)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])