                                        Binary Operation

In [1]:
import numpy as np

In [3]:
arr1 = np.random.randint(1,5, (3,3))

In [4]:
arr2 = np.random.randint(6,10, (3,3))

In [5]:
arr1

array([[3, 3, 2],
       [3, 4, 2],
       [1, 3, 1]])

In [6]:
arr2

array([[6, 8, 6],
       [8, 6, 9],
       [6, 8, 9]])

                                        Arithmetic

In [7]:
arr1 + arr2

array([[ 9, 11,  8],
       [11, 10, 11],
       [ 7, 11, 10]])

In [8]:
arr1/arr2

array([[0.5       , 0.375     , 0.33333333],
       [0.375     , 0.66666667, 0.22222222],
       [0.16666667, 0.375     , 0.11111111]])

In [9]:
arr1 - arr2

array([[-3, -5, -4],
       [-5, -2, -7],
       [-5, -5, -8]])

In [12]:
arr1%arr2

array([[3, 3, 2],
       [3, 4, 2],
       [1, 3, 1]])

In [13]:
arr1 ** arr2

array([[ 729, 6561,   64],
       [6561, 4096,  512],
       [   1, 6561,    1]])

In [14]:
~arr1

array([[-4, -4, -3],
       [-4, -5, -3],
       [-2, -4, -2]])

In [16]:
arr1 | arr2

array([[ 7, 11,  6],
       [11,  6, 11],
       [ 7, 11,  9]])

In [17]:
arr1 & arr2

array([[2, 0, 2],
       [0, 4, 0],
       [0, 0, 1]])

In [18]:
arr1 > arr2

array([[False, False, False],
       [False, False, False],
       [False, False, False]])