In [1]:
import numpy as np

In [4]:
arr = np.random.randint(1,5, (3,4))

In [5]:
arr

array([[4, 4, 3, 4],
       [2, 4, 3, 4],
       [1, 2, 4, 3]])

In [6]:
np.sin(arr)

array([[-0.7568025 , -0.7568025 ,  0.14112001, -0.7568025 ],
       [ 0.90929743, -0.7568025 ,  0.14112001, -0.7568025 ],
       [ 0.84147098,  0.90929743, -0.7568025 ,  0.14112001]])

In [7]:
np.cos(arr)

array([[-0.65364362, -0.65364362, -0.9899925 , -0.65364362],
       [-0.41614684, -0.65364362, -0.9899925 , -0.65364362],
       [ 0.54030231, -0.41614684, -0.65364362, -0.9899925 ]])

In [8]:
np.tanh(arr)

array([[0.9993293 , 0.9993293 , 0.99505475, 0.9993293 ],
       [0.96402758, 0.9993293 , 0.99505475, 0.9993293 ],
       [0.76159416, 0.96402758, 0.9993293 , 0.99505475]])

In [9]:
np.exp(arr)

array([[54.59815003, 54.59815003, 20.08553692, 54.59815003],
       [ 7.3890561 , 54.59815003, 20.08553692, 54.59815003],
       [ 2.71828183,  7.3890561 , 54.59815003, 20.08553692]])

In [12]:
np.power(arr, 2)

array([[16, 16,  9, 16],
       [ 4, 16,  9, 16],
       [ 1,  4, 16,  9]])

In [14]:
np.mean(arr)

3.1666666666666665

In [16]:
np.median(arr)

3.5

In [18]:
np.max(arr)

4