                                        Numpy : Sort & Search

In [1]:
import numpy as np

In [3]:
arr = np.random.randint(1, 20, 10)

In [4]:
arr

array([ 1, 11,  7, 10,  8, 16, 13,  6, 12,  6])

                                        Sort

In [5]:
np.sort(arr)

array([ 1,  6,  6,  7,  8, 10, 11, 12, 13, 16])

In [ ]:
                                        searchsorted()
                                where our next data will go

In [8]:
np.searchsorted(arr, 9)

5

                                    count_nonzero()

arr1 = np.array([1,0,0, 32,323, 0, 0 , 0])

In [18]:
np.count_nonzero(arr1)

3

In [19]:
arr1

array([  1,   0,   0,  32, 323,   0,   0,   0])

In [20]:
np.where(arr1>31)

(array([3, 4]),)

In [23]:
np.extract(arr1>31, arr)

array([10,  8])

                                        Byte Swapping

In [25]:
arr.byteswap()

array([  72057594037927936,  792633534417207296,  504403158265495552,
        720575940379279360,  576460752303423488, 1152921504606846976,
        936748722493063168,  432345564227567616,  864691128455135232,
        432345564227567616])