                                        Numpy : Copy & Views

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10, (2,5))

In [3]:
arr

array([[9, 6, 8, 8, 3],
       [6, 9, 7, 7, 8]])

In [5]:
a = np.copy(arr)

In [6]:
a

array([[9, 6, 8, 8, 3],
       [6, 9, 7, 7, 8]])

In [7]:
b = arr.view()

In [8]:
b

array([[9, 6, 8, 8, 3],
       [6, 9, 7, 7, 8]])

In [9]:
np.argsort(arr)

array([[4, 1, 2, 3, 0],
       [0, 2, 3, 4, 1]])